# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'maingui.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1280, 720)
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.addfile_btn = QtWidgets.QPushButton(Form)
        self.addfile_btn.setObjectName("addfile_btn")
        self.horizontalLayout_2.addWidget(self.addfile_btn)
        self.adddir_btn = QtWidgets.QPushButton(Form)
        self.adddir_btn.setObjectName("adddir_btn")
        self.horizontalLayout_2.addWidget(self.adddir_btn)
        self.verticalLayout_7.addLayout(self.horizontalLayout_2)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.files_tree = QtWidgets.QTreeView(Form)
        self.files_tree.setObjectName("files_tree")
        self.verticalLayout_2.addWidget(self.files_tree)
        self.verticalLayout_5.addLayout(self.verticalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.output_dic_LE = QtWidgets.QLineEdit(Form)
        self.output_dic_LE.setInputMask("")
        self.output_dic_LE.setObjectName("output_dic_LE")
        self.horizontalLayout.addWidget(self.output_dic_LE)
        self.output_dic_btn = QtWidgets.QPushButton(Form)
        self.output_dic_btn.setObjectName("output_dic_btn")
        self.horizontalLayout.addWidget(self.output_dic_btn)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.verticalLayout_7.addLayout(self.verticalLayout_5)
        self.gridLayout_2.addLayout(self.verticalLayout_7, 0, 0, 1, 1)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.batch_lst = QtWidgets.QListWidget(Form)
        self.batch_lst.setObjectName("batch_lst")
        self.verticalLayout.addWidget(self.batch_lst)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.timestamps_chbox = QtWidgets.QCheckBox(self.groupBox)
        self.timestamps_chbox.setObjectName("timestamps_chbox")
        self.gridLayout.addWidget(self.timestamps_chbox, 0, 0, 1, 1)
        self.cue_chbox = QtWidgets.QCheckBox(self.groupBox)
        self.cue_chbox.setObjectName("cue_chbox")
        self.gridLayout.addWidget(self.cue_chbox, 1, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.verticalLayout_6.addLayout(self.verticalLayout_3)
        spacerItem = QtWidgets.QSpacerItem(20, 298, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.clear_btn = QtWidgets.QPushButton(Form)
        self.clear_btn.setObjectName("clear_btn")
        self.verticalLayout_4.addWidget(self.clear_btn)
        self.start_btn = QtWidgets.QPushButton(Form)
        self.start_btn.setObjectName("start_btn")
        self.verticalLayout_4.addWidget(self.start_btn)
        self.verticalLayout_6.addLayout(self.verticalLayout_4)
        self.gridLayout_2.addLayout(self.verticalLayout_6, 0, 1, 1, 1)
        self.gridLayout_2.setColumnStretch(0, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.addfile_btn.setText(_translate("Form", "Add File(s)"))
        self.adddir_btn.setText(_translate("Form", "Add Directory"))
        self.label.setText(_translate("Form", "File(s) List:"))
        self.label_3.setText(_translate("Form", "Output Directory:"))
        self.output_dic_LE.setPlaceholderText(_translate("Form", "Leave blank to Extract to Source Directory"))
        self.output_dic_btn.setText(_translate("Form", "Folder Icon"))
        self.label_2.setText(_translate("Form", "Batch Ectract:"))
        self.groupBox.setTitle(_translate("Form", "For Selected Track(s):"))
        self.timestamps_chbox.setText(_translate("Form", "Extract timestamps"))
        self.cue_chbox.setText(_translate("Form", "Extract cues"))
        self.clear_btn.setText(_translate("Form", "Clear List"))
        self.start_btn.setText(_translate("Form", "Begin"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
